services: 
  telaclass_react-app-dev:
    build:
      context: . 
      dockerfile: Dockerfile.dev
    image: telaclass-i-dev
    container_name: telaclass_react-app-c-dev
    volumes:
      - ./app:/app
      - /Users/filiperocha/pcloud-sync/ufsj/disciplinas/sistemas-supervisórios/material/content-telaclass:/app/public/content-telaclass
    ports: 
      - "3000:3000"
    command: ["/bin/sh", "-c", "npm install && npm run dev"]
    #command: ["/bin/bash", "-c", "tail -f /dev/null"]


  
