FROM node:alpine3.20

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# install npm modules
COPY ./app/package.json ./
RUN npm install

# copy the Next.js application
COPY ./app .

# build the applications
RUN npm run build

# expose port 3000
EXPOSE 3000

# start the application
CMD ["npm", "start"]